# Generated by Django 3.0.6 on 2020-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
