# Generated by Django 3.0.6 on 2020-06-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200612_0538'),
        ('documents', '0003_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.Employee'),
            preserve_default=False,
        ),
    ]
